_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 26ff5da2-651f-4e11-9edb-6b48c4edf035
name: 'D9 Starter Theme'
mail: gilbert@urbaninsight.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
